[package]
name = "message_verifier"
version = "0.1.1"
description = "Rust Message Verifier library compatible with Rails' MessageVerifier and MessageEncryptor"
repository = "https://github.com/mikeycgto/message_verifier"
license = "MIT"
authors = ["Michael J Coyne <mikeycgto@gmail.com>"]
keywords = ["rails", "crypto", "security", "cookies", "sessions"]

[dependencies]
rustc-serialize = "^0.3"
rust-crypto = "^0.2"
rand = "0.3"
error-chain = "0.7.1"
